// Tour step definitions for OptiSys guided experience

export interface TourStep {
  id: number;
  title: string;
  description: string;
  page: string;
  storyText: string;
  layer: string;
}

export const tourSteps: TourStep[] = [
  {
    id: 1,
    title: 'Document Ingestion',
    description: 'Upload governance documents',
    page: '/document-ingestion',
    layer: 'Layer 0 - Data Foundation',
    storyText: 'Welcome to OptiSys! Before procedures can guide work, they must enter the system. Upload a sample document to see how AI extracts procedures, detects overlaps with existing content, and auto-tags metadata. This is Layer 0 - the data foundation.',
  },
  {
    id: 2,
    title: 'Knowledge Base',
    description: 'Select a procedure to follow',
    page: '/knowledge-base',
    layer: 'Layer 1 - Knowledge Repository',
    storyText: 'The Knowledge Base serves as the single source of truth for all governance and procedural content. Documents uploaded in Step 1 become structured procedures here. Select a procedure to follow through the entire operational cycle.',
  },
  {
    id: 3,
    title: 'AI Assistant',
    description: 'Query about the procedure',
    page: '/chat',
    layer: 'Layer 2 - Natural Language Interface',
    storyText: 'The AI Copilot sits on top of the Knowledge Base, giving operators and managers a natural-language interface. Try asking about the procedure you selected - its steps, compliance history, or which facilities struggle with it.',
  },
  {
    id: 4,
    title: 'Procedure Analysis',
    description: 'View procedure details & metrics',
    page: '/procedures',
    layer: 'Layer 3 - Procedure Analytics',
    storyText: 'Now we drill into the specific procedure. This view shows procedure-level analytics: compliance rates, incident correlation, and step-by-step adherence data. Notice how each step\'s completion affects overall quality.',
  },
  {
    id: 5,
    title: 'Field Experience',
    description: 'Complete digital checklist',
    page: '/field-experience',
    layer: 'Layer 4 - Operational Execution',
    storyText: 'Here\'s where operational execution happens. A field worker receives an assigned task with a digital checklist linked to the procedure. Complete the steps and submit - this creates real data that flows back into the system.',
  },
  {
    id: 6,
    title: 'Data Hub',
    description: 'View stored work order record',
    page: '/knowledge-base',
    layer: 'Layer 5 - Data Storage',
    storyText: 'The completed task is now stored in the Data Hub. Every execution becomes a data point - notice your new work order with its compliance status, quality score, and duration. This data feeds the analytics engine.',
  },
  {
    id: 7,
    title: 'Analytics Engine',
    description: 'See analytics impact',
    page: '/',
    layer: 'Layer 6 - Performance Analytics',
    storyText: 'The Analytics Engine correlates procedure adherence with operational outcomes. Your completed task contributes to these metrics - demonstrating the measurable link between process compliance and business results.',
  },
  {
    id: 8,
    title: 'CI Signal Detection',
    description: 'Identify improvement opportunities',
    page: '/',
    layer: 'Layer 7 - Intelligence',
    storyText: 'The system has detected a Continuous Improvement Signal. Notice the amber badge indicating an opportunity to improve the procedure based on field data. This signal was generated by analyzing skip rates, compliance patterns, and quality correlations - the system identified that Step 5 needs refinement.',
  },
  {
    id: 9,
    title: 'Procedure Editing',
    description: 'Update procedure based on insights',
    page: '/procedures',
    layer: 'Layer 8 - Continuous Improvement',
    storyText: 'Based on the CI signal, you can now edit the procedure. The MS Owner (Management System Owner) reviews the AI recommendation and updates step descriptions, criticality levels, and verification requirements. Make a simple edit to demonstrate how insights drive improvements.',
  },
  {
    id: 10,
    title: 'Version History',
    description: 'Track procedure evolution',
    page: '/procedures',
    layer: 'Layer 8 - Continuous Improvement',
    storyText: 'Every procedure edit creates a new version with full audit trail. View the version history showing who made changes, when, and why - including which CI signal triggered the update. This ensures governance and traceability.',
  },
  {
    id: 11,
    title: 'Before/After Comparison',
    description: 'Measure improvement impact',
    page: '/procedures',
    layer: 'Layer 9 - Impact Validation',
    storyText: 'The ultimate proof of continuous improvement: before/after metrics. Compare compliance rates, skip rates, and quality scores between the old version and the updated version. This closes Loop A - showing that field insights drive measurable procedure improvements.',
  },
  {
    id: 12,
    title: 'Complete System Loop',
    description: 'Full operational cycle',
    page: '/',
    layer: 'Layer 10 - Closed Loop',
    storyText: 'You\'ve completed the full OptiSys cycle: Document Upload → Knowledge Base → Field Execution → Analytics → CI Signal → Procedure Update → Measured Improvement. This is operational continuous improvement at scale - where every task execution makes the system smarter.',
  },
];

export const TOTAL_STEPS = tourSteps.length;
